// JUMBLE GAME

#define STR_JUMBLE "JUMBLE"

String jumbledEasy = "JMULBE";
String jumbledMedium = "JLMUBE";
String jumbledHard = "JBLUME";

String currentJumble = "";

// SELECTION PAIR
//

void setup() {
  // SETUP PINS
  // SET CURRENT JUMBLE TO RANDOM JUMBLE DIFFICULTY
  // SELECTION ONE = 1
  // SELECTION TWO = SELECTION ONE + 1
}

void ShuffleLetters() {
  // COPY PAIR.ONE TO CHAR TEMP
  // SET CURRENT JUMBLE SUBSTRING (PAIR.ONE) TO PAIR.TWO
  // SET CURRENT JUMBLE SUBSTRING (PAIR.TWO) TO TEMP (PAIR.ONE)

}

void loop() {
  // DISPLAY CURRENT JUMBLE
  // DISPLAY SELECTION PAIR
  // AWAIT SELECTION INPUT
  // AWAIT SHUFFLE INPUT
  // AFTER SHUFFLE, CHECK CURRENT JUMBLE == STR_JUMBLE
  // IF TRUE, DISPAY WIN!
}
